-- 001_initial.sql — PostgreSQL translation of the complete NexusHOS SQLite schema.
--
-- Sources (SQLite DDL):
--   server/db.js               (core PMS + portfolio schema, indexes)
--   server/audit.js            (HMAC-chained append-only audit log)
--   server/security.js         (rate-limit buckets)
--   server/webhooks.js         (webhook subscriptions/events/delivery attempts)
--   server/routes/booking.js   (direct-booking quotes + idempotency)
--   server/routes/workflows.js (workflow automation + event outbox)
--
-- Deliberate compatibility decisions (keep a future async port behavior-identical):
--   * TEXT stays TEXT. JSON stored as TEXT stays TEXT (not JSONB). ISO 8601
--     timestamp strings stay TEXT (not TIMESTAMPTZ). The application compares
--     ISO strings lexicographically, which remains valid.
--   * Booleans stored as 0/1 integers stay INTEGER (with CHECK (x IN (0, 1))
--     where SQLite declared one); floats (REAL) become DOUBLE PRECISION.
--   * SQLite INTEGER PRIMARY KEY AUTOINCREMENT becomes
--     BIGINT GENERATED BY DEFAULT AS IDENTITY (BY DEFAULT so the SQLite data
--     pump can preserve existing sequence values).
--   * SQLite STRICT tables have no Postgres equivalent and are dropped;
--     Postgres column types already enforce affinity.
--   * SQLite RAISE(ABORT, ...) triggers become PL/pgSQL trigger functions that
--     RAISE EXCEPTION (see the append-only/immutability section below).
--
-- Multi-tenancy staging:
--   * Every BUSINESS table gains
--       organization_id TEXT NOT NULL DEFAULT 'org-default'
--       property_id     TEXT NOT NULL DEFAULT 'prop-default'
--     so existing INSERT statements keep working unchanged until the app layer
--     becomes tenant-aware. Tables that already carry property_id
--     (property_daily_metrics, group_bookings, reputation_reviews, esg_metrics,
--     esg_actions) gain organization_id only.
--   * NOT added to infra tables: sessions, audit_events (audit chain),
--     api_rate_limit_buckets, webhook_subscriptions/events/delivery_attempts
--     (webhook leases), workflow_event_outbox (leased outbox),
--     workflow_audit_events (append-only audit log), schema_migrations.
--   * NOT added to tenant-definition tables: organizations, properties,
--     user_property_memberships, users (global principals; tenancy is expressed
--     through user_property_memberships).

-- ============================================================ core PMS (db.js)

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE,
  password TEXT,
  role TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  must_change_password INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS rooms (
  id TEXT PRIMARY KEY,
  number TEXT UNIQUE,
  type TEXT,
  floor INTEGER,
  status TEXT,
  basePrice DOUBLE PRECISION,
  currentPrice DOUBLE PRECISION,
  amenities TEXT,
  currentGuestName TEXT,
  status_since TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS reservations (
  id TEXT PRIMARY KEY,
  code TEXT,
  guestName TEXT,
  guestEmail TEXT,
  guestPhone TEXT,
  vipTier TEXT,
  roomNumber TEXT,
  roomType TEXT,
  checkIn TEXT,
  checkOut TEXT,
  nights INTEGER,
  guestsCount INTEGER,
  status TEXT,
  channel TEXT,
  totalAmount DOUBLE PRECISION,
  paidAmount DOUBLE PRECISION,
  specialRequests TEXT,
  contactlessCheckInCompleted INTEGER DEFAULT 0,
  actualCheckOut TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS folio_items (
  id TEXT PRIMARY KEY,
  reservation_id TEXT REFERENCES reservations(id),
  date TEXT,
  description TEXT,
  category TEXT,
  amount DOUBLE PRECISION,
  postedBy TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS housekeeping_tasks (
  id TEXT PRIMARY KEY,
  roomNumber TEXT,
  roomType TEXT,
  floor INTEGER,
  taskType TEXT,
  status TEXT,
  assignedTo TEXT,
  priority TEXT,
  etaMinutes INTEGER,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS pricing_rules (
  id TEXT PRIMARY KEY,
  roomType TEXT,
  baseRate DOUBLE PRECISION,
  recommendedRate DOUBLE PRECISION,
  demandFactor DOUBLE PRECISION,
  competitorAvgRate DOUBLE PRECISION,
  occupancyTrigger DOUBLE PRECISION,
  autoApply INTEGER,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS channels (
  id TEXT PRIMARY KEY,
  name TEXT,
  logo TEXT,
  connected INTEGER,
  activeListings INTEGER,
  commissionRate DOUBLE PRECISION,
  lastSync TEXT,
  syncLatency TEXT,
  bookingsThisMonth INTEGER,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS pos_charges (
  id TEXT PRIMARY KEY,
  time TEXT,
  roomNumber TEXT,
  guestName TEXT,
  outlet TEXT,
  items TEXT,
  total DOUBLE PRECISION,
  status TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS guest_profiles (
  id TEXT PRIMARY KEY,
  name TEXT,
  email TEXT,
  phone TEXT,
  vipTier TEXT,
  totalStays INTEGER,
  totalNights INTEGER,
  lifetimeSpend DOUBLE PRECISION,
  preferredRoomType TEXT,
  dietaryPreferences TEXT,
  notes TEXT,
  lastStayDate TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS maintenance_orders (
  id TEXT PRIMARY KEY,
  roomNumber TEXT,
  issueDescription TEXT,
  category TEXT,
  priority TEXT,
  status TEXT,
  reportedBy TEXT,
  assignedEngineer TEXT,
  slaMinutes INTEGER,
  reportedTime TEXT,
  safetyCritical INTEGER DEFAULT 0,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS gl_accounts (
  id TEXT PRIMARY KEY,
  code TEXT,
  name TEXT,
  type TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS journal_entries (
  id TEXT PRIMARY KEY,
  date TEXT,
  description TEXT,
  source TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS journal_lines (
  id TEXT PRIMARY KEY,
  entry_id TEXT REFERENCES journal_entries(id),
  account_id TEXT REFERENCES gl_accounts(id),
  debit DOUBLE PRECISION,
  credit DOUBLE PRECISION,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS inventory_items (
  id TEXT PRIMARY KEY,
  name TEXT,
  category TEXT,
  unit TEXT,
  onHand DOUBLE PRECISION,
  parLevel DOUBLE PRECISION,
  costPerUnit DOUBLE PRECISION,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS vendors (
  id TEXT PRIMARY KEY,
  name TEXT,
  contact TEXT,
  category TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS purchase_orders (
  id TEXT PRIMARY KEY,
  vendorId TEXT,
  itemId TEXT,
  qty DOUBLE PRECISION,
  unitCost DOUBLE PRECISION,
  status TEXT,
  orderDate TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS employees (
  id TEXT PRIMARY KEY,
  name TEXT,
  role TEXT,
  department TEXT,
  shift TEXT,
  hourlyRate DOUBLE PRECISION,
  status TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS shifts (
  id TEXT PRIMARY KEY,
  employeeId TEXT,
  date TEXT,
  start TEXT,
  "end" TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS night_audit_postings (
  business_date TEXT NOT NULL,
  reservation_id TEXT NOT NULL REFERENCES reservations(id),
  folio_item_id TEXT NOT NULL UNIQUE REFERENCES folio_items(id),
  journal_entry_id TEXT REFERENCES journal_entries(id),
  created_at TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default',
  PRIMARY KEY (business_date, reservation_id)
);

CREATE TABLE IF NOT EXISTS folio_journal_postings (
  folio_item_id TEXT PRIMARY KEY REFERENCES folio_items(id),
  journal_entry_id TEXT NOT NULL REFERENCES journal_entries(id),
  created_at TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

-- ------------------------------------------------------- portfolio (db.js) --

CREATE TABLE IF NOT EXISTS organizations (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS properties (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL REFERENCES organizations(id),
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  timezone TEXT NOT NULL,
  currency TEXT NOT NULL,
  locale TEXT NOT NULL,
  total_rooms INTEGER NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_property_memberships (
  user_id TEXT NOT NULL REFERENCES users(id),
  property_id TEXT NOT NULL REFERENCES properties(id),
  role TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (user_id, property_id)
);

CREATE TABLE IF NOT EXISTS property_daily_metrics (
  property_id TEXT NOT NULL REFERENCES properties(id),
  business_date TEXT NOT NULL,
  occupancy_rate DOUBLE PRECISION NOT NULL,
  adr DOUBLE PRECISION NOT NULL,
  revpar DOUBLE PRECISION NOT NULL,
  total_revenue DOUBLE PRECISION NOT NULL,
  goppar DOUBLE PRECISION NOT NULL,
  source TEXT NOT NULL,
  recorded_at TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  PRIMARY KEY (property_id, business_date)
);

CREATE TABLE IF NOT EXISTS group_bookings (
  id TEXT PRIMARY KEY,
  property_id TEXT NOT NULL REFERENCES properties(id),
  group_name TEXT NOT NULL,
  company_name TEXT NOT NULL,
  contact_person TEXT,
  contact_email TEXT,
  rooms_allocated INTEGER NOT NULL,
  rooms_picked_up INTEGER NOT NULL DEFAULT 0,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  release_date TEXT,
  status TEXT NOT NULL,
  group_rate DOUBLE PRECISION NOT NULL,
  banquet_catering_total DOUBLE PRECISION NOT NULL DEFAULT 0,
  total_value DOUBLE PRECISION NOT NULL,
  created_by TEXT REFERENCES users(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT 'org-default'
);

CREATE TABLE IF NOT EXISTS group_room_blocks (
  group_booking_id TEXT NOT NULL REFERENCES group_bookings(id) ON DELETE CASCADE,
  room_type TEXT NOT NULL,
  rooms_allocated INTEGER NOT NULL,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default',
  PRIMARY KEY (group_booking_id, room_type),
  CHECK (rooms_allocated > 0)
);

CREATE TABLE IF NOT EXISTS reputation_reviews (
  id TEXT PRIMARY KEY,
  property_id TEXT NOT NULL REFERENCES properties(id),
  source TEXT NOT NULL,
  external_id TEXT,
  guest_name TEXT NOT NULL,
  rating INTEGER NOT NULL,
  review_date TEXT NOT NULL,
  review_text TEXT NOT NULL,
  sentiment TEXT NOT NULL,
  response_draft TEXT,
  response_text TEXT,
  responded_by TEXT REFERENCES users(id),
  responded_at TEXT,
  imported_at TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT 'org-default'
);

CREATE TABLE IF NOT EXISTS esg_metrics (
  property_id TEXT NOT NULL REFERENCES properties(id),
  date TEXT NOT NULL,
  carbon_per_occupied_room_kg DOUBLE PRECISION NOT NULL,
  energy_kwh_saved DOUBLE PRECISION NOT NULL,
  hvac_auto_setbacks_triggered INTEGER NOT NULL,
  water_consumption_liters DOUBLE PRECISION NOT NULL,
  renewable_energy_percentage DOUBLE PRECISION NOT NULL,
  source TEXT NOT NULL,
  recorded_at TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  PRIMARY KEY (property_id, date)
);

CREATE TABLE IF NOT EXISTS esg_actions (
  id TEXT PRIMARY KEY,
  property_id TEXT NOT NULL REFERENCES properties(id),
  action_type TEXT NOT NULL,
  target TEXT NOT NULL,
  status TEXT NOT NULL,
  requested_by TEXT NOT NULL REFERENCES users(id),
  requested_at TEXT NOT NULL,
  provider TEXT,
  executed_at TEXT,
  result TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default'
);

CREATE INDEX IF NOT EXISTS idx_group_bookings_property_dates
  ON group_bookings(property_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_group_room_blocks_room_type
  ON group_room_blocks(room_type, group_booking_id);
CREATE INDEX IF NOT EXISTS idx_reputation_reviews_property_date
  ON reputation_reviews(property_id, review_date DESC);

-- Created imperatively in db.js after startup repairs; kept as schema here.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_normalized_email
  ON users(lower(trim(email)));
CREATE UNIQUE INDEX IF NOT EXISTS idx_reservations_code_unique
  ON reservations(code);

-- ============================================================ audit (audit.js)

CREATE TABLE IF NOT EXISTS audit_events (
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id TEXT NOT NULL UNIQUE,
  occurred_at TEXT NOT NULL,
  request_id TEXT,
  actor_id TEXT,
  actor_role TEXT,
  action TEXT NOT NULL,
  resource_type TEXT,
  resource_id TEXT,
  outcome TEXT NOT NULL CHECK (outcome IN ('success', 'failure', 'denied')),
  source TEXT NOT NULL,
  network_hash TEXT,
  metadata_json TEXT NOT NULL,
  previous_hash TEXT,
  event_hash TEXT NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_audit_events_occurred_at
  ON audit_events (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_actor
  ON audit_events (actor_id, sequence DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_action
  ON audit_events (action, sequence DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_resource
  ON audit_events (resource_type, resource_id, sequence DESC);

-- ==================================================== security (security.js)

CREATE TABLE IF NOT EXISTS api_rate_limit_buckets (
  scope TEXT NOT NULL,
  bucket_key TEXT NOT NULL,
  window_start_ms BIGINT NOT NULL,
  request_count INTEGER NOT NULL CHECK (request_count >= 0),
  expires_at_ms BIGINT NOT NULL,
  PRIMARY KEY (scope, bucket_key)
);

CREATE INDEX IF NOT EXISTS idx_api_rate_limit_buckets_expiry
  ON api_rate_limit_buckets (expires_at_ms);

-- ==================================================== webhooks (webhooks.js)

CREATE TABLE IF NOT EXISTS webhook_subscriptions (
  id TEXT PRIMARY KEY,
  url TEXT NOT NULL,
  description TEXT,
  event_types_json TEXT NOT NULL,
  secret_encrypted TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS webhook_events (
  id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  occurred_at TEXT NOT NULL,
  request_id TEXT,
  payload_json TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS webhook_delivery_attempts (
  id TEXT PRIMARY KEY,
  event_id TEXT NOT NULL REFERENCES webhook_events(id),
  subscription_id TEXT NOT NULL REFERENCES webhook_subscriptions(id),
  attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),
  status TEXT NOT NULL CHECK (status IN ('Pending', 'Delivering', 'Succeeded', 'Failed')),
  scheduled_at TEXT NOT NULL,
  started_at TEXT,
  completed_at TEXT,
  response_status INTEGER,
  response_body TEXT,
  error_message TEXT,
  signature_version TEXT,
  lease_owner TEXT,
  lease_expires_at TEXT,
  created_at TEXT NOT NULL,
  UNIQUE (event_id, subscription_id, attempt_number)
);

CREATE INDEX IF NOT EXISTS idx_webhook_subscriptions_active
  ON webhook_subscriptions (active, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_webhook_events_type_time
  ON webhook_events (event_type, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_webhook_attempts_due
  ON webhook_delivery_attempts (status, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_webhook_attempts_subscription
  ON webhook_delivery_attempts (subscription_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_webhook_attempts_event
  ON webhook_delivery_attempts (event_id, attempt_number);
-- Created by initializeWebhookSchema alongside the lease columns.
CREATE INDEX IF NOT EXISTS idx_webhook_attempts_lease
  ON webhook_delivery_attempts (status, lease_expires_at, scheduled_at);

-- ==================================================== booking (booking.js)

CREATE TABLE IF NOT EXISTS booking_quotes (
  id TEXT PRIMARY KEY,
  check_in TEXT NOT NULL,
  check_out TEXT NOT NULL,
  nights INTEGER NOT NULL,
  guests_count INTEGER NOT NULL,
  room_type TEXT NOT NULL,
  nightly_rate DOUBLE PRECISION NOT NULL,
  room_total DOUBLE PRECISION NOT NULL,
  tax_rate DOUBLE PRECISION NOT NULL,
  tax_amount DOUBLE PRECISION NOT NULL,
  grand_total DOUBLE PRECISION NOT NULL,
  currency TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Open',
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  consumed_at TEXT,
  reservation_id TEXT REFERENCES reservations(id),
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);
CREATE INDEX IF NOT EXISTS idx_booking_quotes_expiry
  ON booking_quotes(status, expires_at);

CREATE TABLE IF NOT EXISTS booking_idempotency (
  idempotency_key TEXT PRIMARY KEY,
  request_hash TEXT NOT NULL,
  response_status INTEGER NOT NULL,
  response_body TEXT NOT NULL,
  reservation_id TEXT REFERENCES reservations(id),
  created_at TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);
CREATE INDEX IF NOT EXISTS idx_booking_idempotency_created
  ON booking_idempotency(created_at);

-- ==================================================== workflows (workflows.js)

CREATE TABLE IF NOT EXISTS workflow_templates (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  trigger_type TEXT NOT NULL,
  trigger_config TEXT NOT NULL DEFAULT '{}',
  actions TEXT NOT NULL,
  risk_level TEXT NOT NULL CHECK (risk_level IN ('Low', 'Medium', 'High', 'Critical')),
  approval_mode TEXT NOT NULL CHECK (approval_mode IN ('risk-based', 'always', 'never')),
  status TEXT NOT NULL CHECK (status IN ('Active', 'Paused', 'Archived')),
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS workflow_runs (
  id TEXT PRIMARY KEY,
  template_id TEXT NOT NULL REFERENCES workflow_templates(id),
  template_version INTEGER NOT NULL,
  template_snapshot TEXT NOT NULL,
  idempotency_key TEXT NOT NULL UNIQUE,
  request_fingerprint TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Awaiting Approval', 'Running', 'Completed', 'Rejected', 'Failed')),
  risk_level TEXT NOT NULL CHECK (risk_level IN ('Low', 'Medium', 'High', 'Critical')),
  approval_required INTEGER NOT NULL CHECK (approval_required IN (0, 1)),
  context TEXT NOT NULL DEFAULT '{}',
  execution_output TEXT NOT NULL DEFAULT '{}',
  requested_by TEXT NOT NULL,
  requested_at TEXT NOT NULL,
  approved_by TEXT,
  approved_at TEXT,
  completed_at TEXT,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS workflow_tasks (
  id TEXT PRIMARY KEY,
  run_id TEXT REFERENCES workflow_runs(id),
  template_id TEXT REFERENCES workflow_templates(id),
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  department TEXT NOT NULL,
  assigned_to TEXT NOT NULL DEFAULT '',
  priority TEXT NOT NULL CHECK (priority IN ('Low', 'Normal', 'High', 'Urgent')),
  status TEXT NOT NULL CHECK (status IN ('Open', 'In Progress', 'Blocked', 'Completed', 'Cancelled')),
  room_number TEXT,
  due_at TEXT,
  completed_at TEXT,
  metadata TEXT NOT NULL DEFAULT '{}',
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_by TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT 'org-default',
  property_id TEXT NOT NULL DEFAULT 'prop-default'
);

CREATE TABLE IF NOT EXISTS workflow_audit_events (
  id TEXT PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL,
  actor TEXT NOT NULL,
  details TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workflow_event_outbox (
  id TEXT PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL,
  aggregate_id TEXT NOT NULL,
  event_version TEXT NOT NULL,
  context TEXT NOT NULL DEFAULT '{}',
  actor TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Pending', 'Processing', 'Completed', 'Failed')),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  available_at TEXT NOT NULL,
  lease_owner TEXT,
  lease_expires_at TEXT,
  last_error TEXT,
  created_at TEXT NOT NULL,
  completed_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_workflow_templates_status
  ON workflow_templates(status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_workflow_runs_template
  ON workflow_runs(template_id, requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_workflow_runs_status
  ON workflow_runs(status, requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_workflow_tasks_status_due
  ON workflow_tasks(status, due_at);
CREATE INDEX IF NOT EXISTS idx_workflow_tasks_run
  ON workflow_tasks(run_id);
CREATE INDEX IF NOT EXISTS idx_workflow_audit_entity
  ON workflow_audit_events(entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_workflow_event_outbox_due
  ON workflow_event_outbox(status, available_at, lease_expires_at);

-- ======================= append-only / immutability triggers ===============
-- SQLite used RAISE(ABORT, '...') triggers; Postgres needs trigger functions.
-- One shared function per message keeps this compact.

CREATE OR REPLACE FUNCTION reject_append_only_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION reject_immutable_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION '% is immutable', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION reject_run_request_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'workflow run request evidence is immutable';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS audit_events_reject_update ON audit_events;
CREATE TRIGGER audit_events_reject_update
BEFORE UPDATE ON audit_events
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();

DROP TRIGGER IF EXISTS audit_events_reject_delete ON audit_events;
CREATE TRIGGER audit_events_reject_delete
BEFORE DELETE ON audit_events
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();

DROP TRIGGER IF EXISTS webhook_events_reject_update ON webhook_events;
CREATE TRIGGER webhook_events_reject_update
BEFORE UPDATE ON webhook_events
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();

DROP TRIGGER IF EXISTS webhook_events_reject_delete ON webhook_events;
CREATE TRIGGER webhook_events_reject_delete
BEFORE DELETE ON webhook_events
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();

DROP TRIGGER IF EXISTS trg_workflow_audit_events_no_update ON workflow_audit_events;
CREATE TRIGGER trg_workflow_audit_events_no_update
BEFORE UPDATE ON workflow_audit_events
FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation();

DROP TRIGGER IF EXISTS trg_workflow_audit_events_no_delete ON workflow_audit_events;
CREATE TRIGGER trg_workflow_audit_events_no_delete
BEFORE DELETE ON workflow_audit_events
FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation();

DROP TRIGGER IF EXISTS trg_workflow_runs_immutable_request ON workflow_runs;
CREATE TRIGGER trg_workflow_runs_immutable_request
BEFORE UPDATE OF
  template_id, template_version, template_snapshot, idempotency_key,
  request_fingerprint, risk_level, approval_required, context,
  requested_by, requested_at
ON workflow_runs
FOR EACH ROW EXECUTE FUNCTION reject_run_request_mutation();
